### ISSUE TITLE
Update lib to socket.io 2.0.x

### ISSUE THREAD

**Issue by ageapps** [efmr/socket.io-nats#3]
While using `socket.io-nats` with `socket.io` version `2.0.0` i get this error:
```
/app/node_modules/socket.io/lib/socket.js:247
  this.adapter.addAll(this.id, rooms, function(err){
               ^
TypeError: this.adapter.addAll is not a function
    at Socket.join (/app/node_modules/socket.io/lib/socket.js:247:16)
    at Socket.onconnect (/app/node_modules/socket.io/lib/socket.js:302:8)
    at /app/node_modules/socket.io/lib/namespace.js:175:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Its seems to be related o `socket.io`'s version, when using it with version `1.4.5` (the same in the dependencies) it works perfectly fine.

This adapter seems to be pretty usefull in order to scale socket.io backends using NATS, it would be great to release a version supporting `socket.io 2.0.x` versions.

**Comment by dash042** [comment]
I second this issue!!
